change build and start

diff --git a/clickhouse_hass/rootfs/etc/s6-overlay/s6-rc.d/init-clickhouse-server/run b/clickhouse_hass/rootfs/etc/s6-overlay/s6-rc.d/init-clickhouse-server/run
--- a/clickhouse_hass/rootfs/etc/s6-overlay/s6-rc.d/init-clickhouse-server/run
+++ b/clickhouse_hass/rootfs/etc/s6-overlay/s6-rc.d/init-clickhouse-server/run
@@ -8,16 +8,18 @@ set -e
 
 bashio::log.info "Running init script..."
 
+
+
 if [ ! -d "/data/config/clickhouse-server" ]; then
     bashio::log.info "Create dir for configurations clickhouse-server..."
-    mkdir -p /data/config/clickhouse-server
-    cp -r /opt/etc/clickhouse-server/* /data/config/clickhouse-server/
+    mkdir -p /data/config/
+    cp -r /opt/etc/clickhouse-server /data/config
 fi
 
 if [ ! -d "/data/config/clickhouse-client" ]; then
     bashio::log.info "Create dir for configurations clickhouse-client..."
     mkdir -p /data/config/clickhouse-client
-    cp -r /opt/etc/clickhouse-client/* /data/config/clickhouse-client/
+    cp -r /opt/etc/clickhouse-client /data/config/
 fi
 
 if [ ! -d "/data/clickhouse/data" ]; then
@@ -26,12 +28,18 @@ if [ ! -d "/data/clickhouse/data" ]; then
 #    cp -r /var/lib/clickhouse/* /data/clickhouse/data/
 fi
 
-# Указываем ClickHouse использовать конфигурацию из /data
-#bashio::log.info "Использую конфигурацию из /data/config/clickhouse-server..."
-#ln -sf /data/config/clickhouse-server /etc/
-
-# Настраиваем путь для хранения данных в конфигурации
-sed -i 's|<path>/var/lib/clickhouse/</path>|<path>/data/clickhouse/data/</path>|' /data/config/clickhouse-server/config.xml
+# prepare config
+mkdir -p /data/config/clickhouse-server/config.d
+[ -f /data/config/clickhouse-server/config.d/hass.xml ] || echo '<?xml version="1.0" encoding="UTF-8"?><clickhouse></clickhouse>' > /data/config/clickhouse-server/config.d/hass.xml
+xmlstarlet ed -L \
+    -s "/clickhouse" -t elem -n "logger" -v "" \
+    -s "/clickhouse/logger" -t elem -n "level" -v "information" \
+    -s "/clickhouse/logger" -t elem -n "log" \
+    -s "/clickhouse/logger" -t elem -n "errorlog" \
+    -s "/clickhouse/logger" -t elem -n "console" -v "1" \
+    -s "/clickhouse" -t elem -n "path" -v "/data/clickhouse/data" \
+    -s "/clickhouse" -t elem -n "listen_host" -v "0.0.0.0" \
+    /data/config/clickhouse-server/config.d/hass.xml
 
 chown clickhouse:clickhouse /data/clickhouse/data/
 chmod ugo+Xrw -R /data/clickhouse/data/ /data/config/clickhouse-server/ /data/config/clickhouse-client/
